# Generated by Django 4.0.6 on 2022-07-26 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('adddate', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
