# Generated by Django 4.0.6 on 2022-07-27 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0004_alter_employee_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestemployee',
            name='request_status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Waiting', 'Waiting')], default=('Waiting', 'Waiting'), max_length=10),
        ),
    ]
